"""
DANIELA É UMA PESSOA MUITO SUPERSTICIOSA. PARA ELA UM NUMERO É SORTUDO SE ELE CONTEM O DIGITO 2 MAS NAO O DIGITO 7.
ENTAO NA OPNIAO DELA QUANTOS NUMEROS SORTUDOS EXISTEM ENTRE 18644 E 33087, INCLUSIVE OS EXTREMOS?
"""