"""
NA PACATA VILA CAMPESTRE DE PONTEIRONULOVILLE, TODOS OS TELEFONES TEM 6 DIGITOS.
A COMPANHIA TELEFONICA ESTABELECE AS SEGUINTES REGRAS SOBRE OS NUMEROS:
1 - NAO PODE HAVER DOIS DIGITOS CONSECUTIVOS IDENTICOS, PORQUE ISSO EH CHATO
2 - A SOMA DOS DIGITOS TEM QUE SER PAR, PORQUE ISSO EH LEGAL
3 - O ULTIMO DIGITO NAO PODE SER IGUAL AO PRIMEIRO, PORQUE ISSO DA AZAR

ENTAO DADAS ESSAS REGRAS PERFEITAMENTE RAZOAVEIS, BEM PROJETADAS E MADURAS,
QUANTOS NUMEROS DE TELEFONE NA LISTA ABAIXO SAO VALIDOS?

"""